---
title: "R Notebook"
output: html_notebook
---

```{r, echo=FALSE, id="preamble"}
library(rvest)
library(ggplot2)
library(reshape2)

urlHomicides <- "https://en.wikipedia.org/wiki/List_of_countries_by_intentional_homicide_rate"
homicidesDF <- urlHomicides %>% read_html() %>% html_nodes(xpath="//caption[.='UNODC murder rates (per 100,000 inhabitants). Most recent year UNODC has published']/ancestor::table") %>% html_table(fill=TRUE)
homicidesDF <- homicidesDF[[2]]
homicidesDF <- homicidesDF[-c(1),]
#homicidesDF$Count <- as.numeric(gsub('[^\\d]+', '', homicidesDF$Count, perl = TRUE))
homicidesDF$Count <- NULL
homicidesDF$Notes <- NULL
homicidesDF$Subregion <- NULL
homicidesDF$`Year
listed` <- NULL
colnames(homicidesDF)[1] <- "Country"

urlGuns <- "https://en.wikipedia.org/wiki/Estimated_number_of_guns_per_capita_by_country"
gunsDF <- urlGuns %>% read_html() %>% html_nodes(xpath="//th[.='Rank']/ancestor::table") %>% html_table(trim=TRUE, fill=TRUE)
gunsDF <- gunsDF[[1]]
gunsDF$Rank <- NULL
gunsDF$Notes <- NULL
colnames(gunsDF)[2] <- 'Guns per 100 residents'
gunsDF$`Guns per 100 residents` <- as.numeric(gsub('\\[[^\\]]*\\]', '', gunsDF$`Guns per 100 residents`, perl = TRUE))

DF <- merge(homicidesDF, gunsDF)
DF$Country <- factor(DF$Country, levels = DF$Country[order(DF$Rate)])
colnames(DF)[2] <- 'Homicide rate per 100,000'
DF
#DF <- within(DF, Country <- factor(Country, levels = names(sort(table()))))
DF2 <- melt(DF, measure.vars = c("Guns per 100 residents", "Homicide rate per 100,000"))

```


```{r, dpi=600, fig.width = 25, fig.height = 8}
ggplot(DF2, aes(x=Country, y = value, fill=variable)) +
    geom_bar(stat="identity", position="dodge", width = 0.75) + 
    scale_y_continuous(breaks = seq(0, 120, by=10)) + 
    theme(legend.position="top", axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), axis.line = element_line(size = 3, colour = "grey80"))
```

